-- MySQL Script generated by MySQL Workbench
-- Thu Mar 21 23:35:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`mae`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mae` (
  `id_mae` INT NOT NULL AUTO_INCREMENT,
  `nome_mae` VARCHAR(45) NULL,
  `telefone_mae` VARCHAR(45) NULL,
  `endereco_mae` VARCHAR(45) NULL,
  `data_nasc_mae` VARCHAR(45) NULL,
  PRIMARY KEY (`id_mae`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bebe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bebe` (
  `id_bebe` INT NOT NULL AUTO_INCREMENT,
  `nome_bebe` VARCHAR(45) NOT NULL,
  `peso_bebe` DOUBLE NOT NULL,
  `altura_bebe` DOUBLE NULL,
  `data_nascimento_bebe` DATETIME NULL,
  `mae_id_mae` INT NOT NULL,
  PRIMARY KEY (`id_bebe`, `mae_id_mae`),
  INDEX `fk_bebe_mae1_idx` (`mae_id_mae` ASC) VISIBLE,
  CONSTRAINT `fk_bebe_mae1`
    FOREIGN KEY (`mae_id_mae`)
    REFERENCES `mydb`.`mae` (`id_mae`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `nome_medico` VARCHAR(45) NULL,
  `especialidade_medico` VARCHAR(45) NULL,
  `telefone_medico` VARCHAR(45) NULL,
  `CRM_medico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CRM_medico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atendimento_parto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atendimento_parto` (
  `bebe_id_bebe` INT NOT NULL,
  `bebe_mae_id_mae` INT NOT NULL,
  `medico_CRM_medico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bebe_id_bebe`, `bebe_mae_id_mae`, `medico_CRM_medico`),
  INDEX `fk_bebe_has_medico_medico1_idx` (`medico_CRM_medico` ASC) VISIBLE,
  INDEX `fk_bebe_has_medico_bebe1_idx` (`bebe_id_bebe` ASC, `bebe_mae_id_mae` ASC) VISIBLE,
  CONSTRAINT `fk_bebe_has_medico_bebe1`
    FOREIGN KEY (`bebe_id_bebe` , `bebe_mae_id_mae`)
    REFERENCES `mydb`.`bebe` (`id_bebe` , `mae_id_mae`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bebe_has_medico_medico1`
    FOREIGN KEY (`medico_CRM_medico`)
    REFERENCES `mydb`.`medico` (`CRM_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acidente` (
  `idacidente` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idacidente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apolice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apolice` (
  `idapolice` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idapolice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carro` (
  `idcarro` INT NOT NULL AUTO_INCREMENT,
  `cliente_id_cliente` INT NOT NULL,
  `acidente_idacidente` INT NOT NULL,
  `apolice_idapolice` INT NOT NULL,
  PRIMARY KEY (`idcarro`, `cliente_id_cliente`, `apolice_idapolice`),
  INDEX `fk_carro_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_carro_acidente1_idx` (`acidente_idacidente` ASC) VISIBLE,
  INDEX `fk_carro_apolice1_idx` (`apolice_idapolice` ASC) VISIBLE,
  CONSTRAINT `fk_carro_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carro_acidente1`
    FOREIGN KEY (`acidente_idacidente`)
    REFERENCES `mydb`.`acidente` (`idacidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carro_apolice1`
    FOREIGN KEY (`apolice_idapolice`)
    REFERENCES `mydb`.`apolice` (`idapolice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `data_vencimento` DATETIME NULL,
  `data_pagamento` DATETIME NULL,
  `apolice_idapolice` INT NOT NULL,
  PRIMARY KEY (`id_pagamento`, `apolice_idapolice`),
  INDEX `fk_pagamento_apolice1_idx` (`apolice_idapolice` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_apolice1`
    FOREIGN KEY (`apolice_idapolice`)
    REFERENCES `mydb`.`apolice` (`idapolice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
